# Generated by Django 5.2.4 on 2025-07-26 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_product_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="supplier",
            name="vendor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.vendor",
            ),
        ),
    ]
